name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
  save:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: save docker image
      run: docker save -o angular-material-calendar.tar upbytes/angular-material-calendar-demo:$(date +%s)
      
