name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
           docker build --tag my-image-name:1 .
           docker save -o angular-material-calendar.tar upbytes/angular-material-calendar-demo:1
